spring:
  datasource:
    password: B1xzzRWhCiKAp4Up0gnsQl2xtXJYH0HE
    url: jdbc:postgresql://B1xzzRWhCiKAp4Up0gnsQl2xtXJYH0HE-a.frankfurt-postgres.render.com:5432/database_test_pe9s
    username: database_test_pe9s_user
