spring:
  profiles:
    active: development
  jpa:
    generate-ddl: true
    open-in-view: false
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
    org:
      springframework:
        # web: DEBUG
        security: INFO
server:
  address: 0.0.0.0
  port: 8080
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
sentry:
  dsn: https://dcc135c20d90723b5db9ed3ede7eae02@o4507741689806848.ingest.de.sentry.io/4507741712416848
  exception-resolver-order: -2147483647
  # Set traces_sample_rate to 1.0 to capture 100%
  # of transactions for tracing.
  # We recommend adjusting this value in production.
  tracesSampleRate: 1.0
user:
  email: hexlet@example.com
  password: qwerty