spring:
  datasource:
    url: jdbc:postgresql://dpg-colafju3e1ms738a3u10-a.ohio-postgres.render.com/render_db1
    username: render_db1_user
    password: qjADkhhCSu7WiRwmaoYauuhU6tDABhjp
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: INFO
    org:
      springframework:
        # web: DEBUG
        security: INFO