spring:
  datasource:
    #    url: "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=TRUE;TRACE_LEVEL_FILE=3"
    #    url: "jdbc:h2:file:./development_H2.db;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    url: "jdbc:h2:file:./H2-db;MODE=PostgreSQL;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    #    url: "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE;DEFAULT_NULL_ORDERING=HIGH"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    #open-in-view: false
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    web: DEBUG
    hexlet:
      code: DEBUG
    org:
      springframework: DEBUG
#        web: DEBUG
#        security: TRACE
      hibernate: DEBUG
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
