spring:
  datasource:
    url: "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=TRUE;TRACE_LEVEL_FILE=3"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    #open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: DEBUG
    com.zaxxer.hikari: WARN
    web: WARN
    hexlet:
      code: WARN
    org:
      springframework:
      #        web: DEBUG
              security: TRACE
      hibernate: WARN
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
