spring:
  profiles:
    active: development
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
    org:
      springframework:
        # web: DEBUG
        security: INFO
server:
  address: 0.0.0.0
  port: 8080
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem