spring:
  datasource:
    url: "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: ERROR
    org:
      springframework:
        # web: DEBUG
        security: INFO
